name: oops
version: 0.0.1
author: Daniel Davidson <dbdavidson@yahoo.com>
dependencies:
  browser: ">=0.9.0 < 0.10.0"

  path: ">=0.9.0 < 0.10.0"

  polymer: ">=0.9.0 < 0.10.0"

  logging: ">=0.7.1"

# custom <oops dependencies>
# end <oops dependencies>

dev_dependencies:
# custom <oops dev dependencies>
# end <oops dev dependencies>


